version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/myapp
      # - ./public/assets:/myapp/public/assets
      - upload-data:/myapp/public/uploads
      - assets:/myapp/public/assets/
      # - ./production_assets:/myapp/public/assets/
    env_file: .env.web
    command: bundle exec unicorn -c config/containers/unicorn.rb -E production;
    environment:
      - RAILS_ENV=production
      - RAILS_ROOT=/myapp
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample_postgres_production
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
  nginx:
    image: nginx
    links:
      - web
    volumes:
      - ./config/nginx.conf:/etc/nginx/sites-enabled/infomark.conf:ro
      - assets:/assets/
    ports:
      - "3001:80"

volumes:
  upload-data:
  postgres-data:
  assets:


