# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ed541a599b87b1e570083a78d2e33821cf770f9fd0ef9904daf5d95f83849c393214f0f51562a47563933229b45dc7f31e4003ef8a1ce8edc707949debd2ee6
  domain_name: <%= ENV["INFOMARK_DOMAIN_NAME"] %>
  upload_dir: <%= ENV["INFOMARK_UPLOAD_DIR"] %>

test:
  secret_key_base: 368f6f5bb1d5f33c4645da48548931b96cca44107c3b2fef8460a850b2bffb7c851002ac1f3e05822f8ca667dad682f34b3c06aba7d3d2fe65dbaa253ac08b1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["INFOMARK_DOMAIN_NAME"] %>
  upload_dir: <%= ENV["INFOMARK_UPLOAD_DIR"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["INFOMARK_DOMAIN_NAME"] %>
  upload_dir: <%= ENV["INFOMARK_UPLOAD_DIR"] %>
